#!/bin/bash
# Promotes the root (Beta/dev) build into stable/ (the frozen Stable snapshot served by
# index.html's Stable cards). Run this from the repo root when you've tested the root
# build on ?env=dev and are ready to make it the new Stable baseline.
#
# stable/ mirrors the root file tree one level deeper, so relative paths (assets/,
# index.html links, CSS url()s) need an extra "../" — this script re-applies those fixes
# after copying, so it's safe to re-run any time.
set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf stable/map.html stable/nst stable/shared
cp map.html stable/map.html
cp -R nst stable/nst
cp -R shared stable/shared

# stable/map.html and stable/nst/*.html are one level deeper than their root counterparts.
# The location.href rule fixes the post-sign-in redirect specifically — it's a bare JS string
# literal ('index.html'), not an HTML attribute, so the href="..." rule above doesn't catch it.
# Missing this once sent a freshly-signed-in Stable user to a 404 at stable/index.html.
sed -i '' \
  -e 's/src="assets\//src="..\/assets\//g' \
  -e 's/href="index\.html"/href="..\/index.html"/g' \
  -e 's/url(assets\//url(..\/assets\//g' \
  -e "s/location\.href='index\.html'/location.href='..\/index.html'/g" \
  stable/map.html

for f in stable/nst/*.html; do
  sed -i '' -e 's/href="\.\.\/index\.html"/href="..\/..\/index.html"/g' "$f"
done

# stable/nst/css/nst-shared.css is 3 levels deep from repo root under stable/.
sed -i '' -e "s#url('\.\./\.\./assets/#url('../../../assets/#g" stable/nst/css/nst-shared.css

# nst/js/auth.js's post-sign-in redirect (the NST login modal, separate from map.html's own
# account gate above) is also a bare JS string literal ('../index.html'), not an HTML attribute
# — same bug class as the location.href fix above, just in a different file. Missed this once
# too: it sent a freshly-signed-in Stable Shop DB user to the same stable/index.html 404.
sed -i '' -e "s/location\.href = '\.\.\/index\.html';/location.href = '..\/..\/index.html';/g" stable/nst/js/auth.js

# Stable must always be production data, full stop — no ?env=dev override, no sessionStorage
# stickiness, no dev-mode banner. Root's env-detection logic is meant for Beta/local dev testing;
# leaving it in stable/ meant a browser tab that had visited Beta (?env=dev) earlier could bleed
# dev-mode into Stable too (e.g. a bare stable/map.html URL with no query string inherits the
# sticky flag). Hardcode both copies to prod instead of sed-patching the dev-switching logic.
python3 - <<'PYEOF'
path = 'stable/map.html'
text = open(path, encoding='utf-8').read()
start = text.index("// Dev/prod switch by hostname")
end = text.index("let currentUser=null;")
replacement = (
    "// Stable is always production data — no ?env=dev override, no sticky flag, no banner\n"
    "// (that logic only exists in the root map.html for Beta/local testing). Hardcoded here\n"
    "// on purpose, regenerated by tools/promote-stable.sh on every promotion.\n"
    "const SUPABASE_URL='https://mdznetxdongeinthqgtp.supabase.co';\n"
    "const SUPABASE_ANON_KEY='sb_publishable_EUskeusj4mfPYeJUuDJIcQ_fHbBHPS9';\n"
    "const sbClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);\n"
    "const _forcedDev=false; // referenced elsewhere (e.g. the map's \"open full edit\" deep link)\n"
)
text = text[:start] + replacement + text[end:]
open(path, 'w', encoding='utf-8').write(text)
PYEOF

cat > stable/shared/supabase-env.js <<'EOF'
// Stable is always production data — no ?env=dev override, no sticky flag, no banner. The
// dev/prod-switching logic lives only in the root shared/supabase-env.js (for Beta/local
// testing); this copy is hardcoded so Stable can never accidentally show dev data, regardless
// of query params or leftover sessionStorage state from testing Beta in the same browser tab.
// Regenerated by tools/promote-stable.sh on every promotion — don't hand-edit.
export const SUPABASE_ENV = { url: 'https://mdznetxdongeinthqgtp.supabase.co', key: 'sb_publishable_EUskeusj4mfPYeJUuDJIcQ_fHbBHPS9' };
export const IS_STAGING = false;
EOF

echo "stable/ updated from root. Review with 'git diff stable/' before committing."
