// Stable is always production data — no ?env=dev override, no sticky flag, no banner. The
// dev/prod-switching logic lives only in the root shared/supabase-env.js (for Beta/local
// testing); this copy is hardcoded so Stable can never accidentally show dev data, regardless
// of query params or leftover sessionStorage state from testing Beta in the same browser tab.
// Regenerated by tools/promote-stable.sh on every promotion — don't hand-edit.
export const SUPABASE_ENV = { url: 'https://mdznetxdongeinthqgtp.supabase.co', key: 'sb_publishable_EUskeusj4mfPYeJUuDJIcQ_fHbBHPS9' };
export const IS_STAGING = false;
